### ISSUE TITLE
disallow: configuration option

### ISSUE THREAD

**Issue by simonw** [simonw/datasette-block-robots#2]
I'd like to use this plugin on some of my Cloud Run hosted projects to stop crawlers from keeping the instance awake all month and costing me lots of money.

This should do the trick:

```
User-agent: *
Disallow: /dbname
````

With a line for each database.

**Comment by simonw** [comment]
Configuration in `metadata.yml` can look like this:
```yaml
plugins:
  datasette-block-robots:
    block_databases: true
```
This can be `true` for block-them-all, or it can be a list of specific databases to just block certain ones.
```yaml
plugins:
  datasette-block-robots:
    block_databases: ["mydb"]
```

**Comment by simonw** [comment]
Actually I think I'm going to solve this in a more general way. I'll add a `disallow` configuration option which is a line of things to disallow. It will look like this:
```yaml
plugins:
  datasette-block-robots:
    disallow:
    - /dbname
```
