### ISSUE TITLE
Ability to allow specific robots (by complete customizations of robots.txt)

### ISSUE THREAD

**Issue by simonw** [simonw/datasette-block-robots#3]
From my logs it looks like `BLEXBot` is hammering one of my Cloud Run instances and costing money. GoogleBot is much better behaved. Would be useful to be able to allow specific known-well-behaved crawlers.

**Comment by simonw** [comment]
I'm going to solve this by allowing the config file to contain the literal robots.txt it wants to use:
```yaml
plugins:
  datasette-block-robots:
    literal: |-
      User-agent: *
      Disallow: /
      User-agent: Bingbot
      User-agent: Googlebot
      Disallow:
```
